FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY src/ToolboxV15/ToolboxServer/ToolboxApi/ ./src/ToolboxV15/ToolboxServer/ToolboxApi/
RUN dotnet restore ./src/ToolboxV15/ToolboxServer/ToolboxApi/ToolboxApi.csproj
RUN dotnet publish ./src/ToolboxV15/ToolboxServer/ToolboxApi/ToolboxApi.csproj -c Release -o /app /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "ToolboxApi.dll"]