server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /panel/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /panel/index.html;
    }

    location = /panel {
        return 301 /panel/;
    }

    location / {
        try_files $uri /index.html;
    }
}